# Generated by Django 4.0.4 on 2022-05-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_post_user_delete_client_delete_criptos_post_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario',
        ),
    ]
