# Generated by Django 4.0.4 on 2022-06-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_rename_message_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emisor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='receptor',
            field=models.CharField(max_length=50),
        ),
    ]
