# Generated by Django 4.0.4 on 2022-06-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_alter_message_emisor_alter_message_receptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='posteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(default='', max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=None)),
            ],
        ),
    ]
