# Generated by Django 4.0.4 on 2022-06-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_posteos'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='message',
        ),
        migrations.DeleteModel(
            name='posteos',
        ),
    ]
