# Generated by Django 4.0.4 on 2022-06-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_rename_receptor_message_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='usuario',
            new_name='emisor',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='post',
            new_name='receptor',
        ),
    ]
