# Generated by Django 4.0.4 on 2022-06-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0013_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='emisor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receptor',
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='message',
        ),
    ]
