# Generated by Django 4.0.4 on 2022-06-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0017_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='img',
            old_name='img',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
