# Generated by Django 4.0.4 on 2022-06-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0019_delete_img_post_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='foto',
            new_name='image',
        ),
    ]
